{
  "hash": "8ef7df8028028e9911fabb4b83a7db96",
  "result": {
    "markdown": "---\ntitle: \"DID\"\nauthor: \"Caio Lopes\"\ndate: \"2025-04-19\"\ncategories: [Ensino]\n#image: \"image.jpg\"\n---\n\n\n# Introdução\n\nNormalmente, o pesquisador não tem acesso a dados de experimentos controlados e randomizados. Mesmo assim o infêrencial causal continua sendo de interesse. O método de diferenças em diferenças utiliza a dinamica temporal para dirimir a víes de seleção. A sua beleza reside na simplicidade com que, sob certas hipóteses, consegue isolar o efeito de um tratamento, controlando por fatores não observáveis que poderiam confundir a nossa análise.\n\nNeste post, vamos mergulhar na intuição por trás do DiD. Começaremos com a intuição do método. Em seguida, desvendaremos como o DiD elimina o viés de seleção, qual a sua hipótese fundamental -- as tendências paralelas -- e como podemos testá-la visualmente através de estudos de eventos. Por fim, abordaremos uma extensão robusta, as Triplas Diferenças (DDD), e ilustraremos todos esses conceitos com dados simulados, mostrando o poder do método na prática.\n\n# A desoneração da folha de pagamentos\n\nNo início dos anos 2010, o governo brasileiro enfrentava preocupações sobre a competitividade da indústria nacional e o custo elevado da mão de obra. A contribuição previdenciária patronal de 20% sobre a folha de salários era vista como um entrave à geração de empregos, especialmente em setores intensivos em trabalho. Em resposta, o governo implementou a desoneração da folha através da Lei nº 12.546/2011, que entrou em vigor em 2012.\n\nA política permitiu que empresas de setores específicos optassem por pagar uma contribuição sobre a receita bruta (com alíquotas variando de 1% a 4,5%) em vez dos tradicionais 20% sobre a folha.\n\nDo ponto de vista da inferência causal, essa política criou uma situação quasi-experimental ideal para aplicação do DiD:\n\n1.  **Grupo de Tratamento**: Empresas em setores desonerados\n2.  **Grupo de Controle**: Empresas em setores não desonerados\n3.  **Período Pré-Tratamento**: 2007-2011 (antes da implementação)\n4.  **Período Pós-Tratamento**: 2012-2015 (após a implementação)\n5.  **Outcome de Interesse**: Número de trabalhadores empregados\n\n## A Intuição do Método DiD\n\n### Por que Comparações Simples Falham?\n\nImagine que queremos avaliar se a desoneração aumentou o emprego. Poderíamos ser tentados a fazer duas comparações simples:\n\n1.  **Comparação Cross-Sectional (2012-2017)**: Comparar o emprego médio nos setores desonerados com os não desonerados após a política. O problema? Os setores desonerados (como TI e construção civil) já eram naturalmente mais intensivos em mão de obra *antes* da política. Essa diferença estrutural entre os setores é o que chamamos de **viés de seleção** ou **efeito fixo de grupo**.\n\n2.  **Comparação Temporal (Setores Desonerados)**: Comparar o emprego nos setores desonerados antes e depois de 2012. O problema? Entre 2008 e 2017, a economia brasileira passou por ciclos de crescimento e recessão que afetaram todos os setores. Atribuir toda a mudança à desoneração ignoraria essas **tendências temporais comuns**.\n\n### O DiD\n\nO DiD combina ambas as abordagens de forma engenhosa. A primeira diferença (temporal) para cada grupo remove os efeitos fixos. A segunda diferença (entre grupos) remove as tendências temporais comuns. O que sobra é o efeito causal da política.\n\nVamos decompor isso com um exemplo intuitivo usando símbolos:\n\n| **Grupo** | **Antes (2008-2011)** | **Depois (2012-2017)** | **Diferença Temporal** |\n|------------------|------------------|------------------|------------------|\n| **Setores Desonerados** | D + S | D + S + T + E | T + E |\n| **Setores Não Desonerados** | S | S + T | T |\n| **Diferença entre Grupos** | D | D + E | **E** ← **DiD** |\n\n**Legenda dos Efeitos:**\n\n-   **D**: Efeito fixo dos setores desonerados (ex: TI e construção são naturalmente mais intensivos em mão de obra)\n\n-   **S**: Efeito fixo dos setores não desonerados (baseline comum)\n\n-   **T**: Tendência temporal comum (crescimento/recessão econômica que afeta todos os setores)\n\n-   **E**: **Efeito causal da desoneração** (o que queremos estimar)\n\n**Como o DiD Funciona:**\n\n1.  **Primeira diferença temporal** elimina os efeitos fixos (D e S desaparecem)\n2.  **Segunda diferença entre grupos** elimina a tendência temporal comum (T desaparece)\n3.  **O que sobra é E**: o efeito causal puro da desoneração\n\nFormalmente, o estimador DiD é:\n\n$$\nDiD = [E[Y | D=1, Post] - E[Y | D=1, Pre]] - [E[Y | D=0, Post] - E[Y | D=0, Pre]]\n$$ \\## Como o DiD Elimina o Viés de Seleção do ATT\n\n### O Problema Fundamental da Inferência Causal\n\nO que realmente queremos estimar é o **Efeito Médio do Tratamento sobre os Tratados (ATT)**:\n\n$$\nATT = E[Y^{1} | D=1] - E[Y^{0} | D=1]\n$$\n\nOnde $Y^{1}$ é o emprego com desoneração e $Y^{0}$ é o emprego sem desoneração. O primeiro termo é observável (vemos o emprego nos setores desonerados após 2012). O problema é o segundo termo: o emprego **contrafactual** que teria ocorrido nos setores desonerados se a política não tivesse sido implementada. Esse contrafactual é, por definição, inobservável.\n\nComo agora acompanhamos as unidades no tempo, podemos reescrever nosso ATT como:\n\n$$\nATT = E[Y^{1} | D=1, Post] - E[Y^{0} | D=1, Post]\n$$\n\nUma vez que se $D=1$ estamos considerando o período pós tratamento.\n\n### A Hipótese de Tendências Paralelas\n\nO DiD resolve esse problema fazendo uma hipótese crucial: na ausência do tratamento, a trajetória do emprego nos setores desonerados teria sido a mesma que a trajetória observada nos setores não desonerados. Formalmente:\n\n$$\nE[Y^{0} | D=1, Post] - E[Y^{0} | D=1, Pre] = E[Y^{0} | D=0, Post] - E[Y^{0} | D=0, Pre=1]\n$$\n\nEm palavras: a mudança no emprego para os setores controle é um bom proxy para a mudança que *teria ocorrido* nos setores desonerados na ausência da política. Se essa hipótese for válida, o DiD identifica perfeitamente o ATT.\n\n### Decomposição do Estimador\n\nPodemos decompor o estimador DiD da seguinte forma: $$\nDiD = ATT + [E[Y^{0}|D=1,Post] - E[Y^{0}|D=1,Pre]] - [E[Y^{0} |D=0,Post] - E[Y^{0}|D=0,Pre]]\n$$ O segundo termo é o viés de tendências não-paralelas. Se as tendências forem paralelas (segundo termo = 0), então **DiD = ATT**. O método usa a tendência do grupo controle para construir o contrafactual não observado do grupo tratado.\n\nPara entender como chegamos na decomposição acima, vamos rescrever o estimador DiD por meio dos resultados potenciais:\n\n$$\nDiD = [E[Y^{1} | D=1, Post] - E[Y^{0} | D=1, Pre]] - [E[Y^{0} | D=0, Post] - E[Y^{0} | D=0, Pre]]\n$$ Somando e subtraindo do lado direito da equação por $[E[Y^{0} | D=1, Post]$, temos:\n\n$$\nDiD = [E[Y^{1} | D=1, Post] - E[Y^{0} | D=1, Pre]] - [E[Y^{0} | D=0, Post] - E[Y^{0} | D=0, Pre]] + ([E[Y^{0} | D=1, Post] - [E[Y^{0} | D=1, Post])\n$$ Rearranjando as expressões temos:\n\n$$\nDiD = [E[Y^{1} | D=1, Post] - [E[Y^{0} | D=1, Post] + [E[Y^{0} | D=1, Post] - E[Y^{0} | D=1, Pre]] - [E[Y^{0} | D=0, Post] - E[Y^{0} | D=0, Pre]]  \n$$ Em que:\n\n-   $[E[Y^{1} | D=1, Post] - [E[Y^{0} | D=1, Post]= ATT$\n-   $[E[Y^{0} | D=1, Post] - E[Y^{0} | D=1, Pre]] - [E[Y^{0} | D=0, Post] - E[Y^{0} | D=0, Pre]]$ é o viés causado por tendencias não paralelas\n\n### Outras Hipóteses Necessárias\n\nAlém de tendências paralelas, o DiD requer:\n\n1.  **SUTVA (Stable Unit Treatment Value Assumption)**: O tratamento de uma empresa não afeta o resultado de outras\n2.  **Exogeneidade do Timing**: A implementação em 2012 não foi antecipada de forma a alterar comportamentos pré-tratamento\n3.  **Composição Estável**: A composição dos setores não muda drasticamente (ex: empresas não migram entre setores)\n\n## Do Cálculo Manual à Regressão OLS\n\nAté agora, estimamos o DiD calculando manualmente as diferenças de médias. Mas há uma forma mais elegante e flexível: **regressão por Mínimos Quadrados Ordinários (OLS)**. Surpreendentemente, uma regressão simples com uma interação recupera *exatamente* o mesmo estimador DiD.\n\n### A Especificação de Regressão\n\nConsidere o seguinte modelo de regressão linear:\n\n$$Y_{it} = \\beta_0 + \\beta_1 \\text{Desonerado}_i + \\beta_2 \\text{Post}_t + \\beta_3 (\\text{Desonerado}_i \\times \\text{Post}_t) + \\varepsilon_{it}$$\n\nOnde: - $Y_{it}$ é o número de trabalhadores na empresa $i$ no período $t$ - $\\text{Desonerado}_i = 1$ se a empresa está em setor desonerado, 0 caso contrário - $\\text{Post}_t = 1$ se o período é pós-2012, 0 caso contrário - $\\text{Desonerado}_i \\times \\text{Post}_t$ é a **interação** entre tratamento e período\n\n**Interpretação dos Coeficientes:** - $\\beta_0$: Emprego médio nos setores não desonerados antes de 2012 (grupo base) - $\\beta_1$: Diferença fixa entre setores desonerados e não desonerados (efeito fixo de grupo) - $\\beta_2$: Mudança temporal comum a todos os setores (tendência temporal) - $\\beta_3$: **Efeito causal da desoneração (DiD/ATT)**\n\n### Demonstração Matemática: $\\beta_3 = \\text{DiD}$\n\nVamos provar que $\\beta_3$ é exatamente igual ao estimador DiD que calculamos manualmente.\n\n**Passo 1: Valores Esperados para Cada Grupo-Período**\n\nUsando a equação de regressão, podemos calcular o valor esperado de $Y$ para cada combinação de grupo e período:\n\n| Grupo | Período | Desonerado | Post | Interação | $E[Y]$ |\n|------------|------------|------------|------------|------------|------------|\n| Não Desonerado | Antes | 0 | 0 | 0 | $\\beta_0$ |\n| Não Desonerado | Depois | 0 | 1 | 0 | $\\beta_0 + \\beta_2$ |\n| Desonerado | Antes | 1 | 0 | 0 | $\\beta_0 + \\beta_1$ |\n| Desonerado | Depois | 1 | 1 | 1 | $\\beta_0 + \\beta_1 + \\beta_2 + \\beta_3$ |\n\n**Passo 2: Primeira Diferença (Temporal) para Cada Grupo**\n\n*Setores Desonerados:* $$\\Delta_{\\text{Desonerado}} = (\\beta_0 + \\beta_1 + \\beta_2 + \\beta_3) - (\\beta_0 + \\beta_1) = \\beta_2 + \\beta_3$$\n\n*Setores Não Desonerados:* $$\\Delta_{\\text{Não Desonerado}} = (\\beta_0 + \\beta_2) - \\beta_0 = \\beta_2$$\n\n**Passo 3: Segunda Diferença (DiD)**\n\n$$\\text{DiD} = \\Delta_{\\text{Desonerado}} - \\Delta_{\\text{Não Desonerado}} = (\\beta_2 + \\beta_3) - \\beta_2 = \\beta_3$$\n\n**Conclusão:** O coeficiente da interação $\\beta_3$ é **exatamente** o estimador DiD!\n\n### Visualização da Decomposição\n\nPodemos reorganizar a tabela acima para ver claramente como cada componente contribui:\n\n| Grupo | Período | Valor Esperado | Decomposição |\n|------------------|------------------|------------------|------------------|\n| Não Desonerado | Antes | $\\beta_0$ | Baseline |\n| Não Desonerado | Depois | $\\beta_0 + \\beta_2$ | Baseline + Tendência |\n| Desonerado | Antes | $\\beta_0 + \\beta_1$ | Baseline + Efeito Fixo |\n| Desonerado | Depois | $\\beta_0 + \\beta_1 + \\beta_2 + \\beta_3$ | Baseline + Efeito Fixo + Tendência + **DiD** |\n\nNote que: - $\\beta_0$ cancela em todas as diferenças - $\\beta_1$ cancela na diferença temporal - $\\beta_2$ cancela na diferença entre grupos - $\\beta_3$ sobrevive como o único termo não cancelado\n\n## Aplicação Prática com Dados Simulados\n\nPara tornar os conceitos mais concretos, vamos simular dados de painel com 100 empresas (50 em setores desonerados, 50 em setores controle) ao longo de 9 anos (2007-2015). A desoneração é implementada em 2012 e tem um efeito verdadeiro de **+25 trabalhadores**.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Configurar seed para reprodutibilidade\nset.seed(42)\n\n# Parâmetros da simulação\nn_empresas <- 100\nn_anos <- 9  # 2007-2015\nano_inicio <- 2007\nano_desoneracao <- 2012\n\n# Metade das empresas em setores desonerados\nn_desonerado <- n_empresas / 2\n\n# Criar data frame vazio\ndados <- data.frame()\n\nfor (i in 1:n_empresas) {\n  # Determinar se empresa está em setor desonerado\n  desonerado <- ifelse(i <= n_desonerado, 1, 0)\n  \n  # Efeito fixo da empresa\n  # Setores desonerados têm baseline maior (mais intensivos em mão de obra)\n  efeito_fixo <- 100 + (30 * desonerado) + rnorm(1, mean = 0, sd = 10)\n  \n  for (t in 0:(n_anos - 1)) {\n    ano <- ano_inicio + t\n    \n    # Tendência temporal comum (crescimento econômico)\n    tendencia_temporal <- 5 * t\n    \n    # Efeito da desoneração (apenas após 2012 para setores desonerados)\n    efeito_desoneracao <- ifelse(desonerado == 1 & ano >= ano_desoneracao, 25, 0)\n    \n    # Ruído aleatório\n    erro <- rnorm(1, mean = 0, sd = 5)\n    \n    # Número de trabalhadores\n    n_trabalhadores <- efeito_fixo + tendencia_temporal + efeito_desoneracao + erro\n    \n    # Criar variável post\n    post <- ifelse(ano >= ano_desoneracao, 1, 0)\n    \n    # Criar variável de interação\n    desoneracao <- desonerado * post\n    \n    # Adicionar linha ao data frame\n    dados <- rbind(dados, data.frame(\n      empresa_id = i,\n      ano = ano,\n      tempo = t,\n      desonerado = desonerado,\n      post = post,\n      desoneracao = desoneracao,\n      n_trabalhadores = n_trabalhadores\n    ))\n  }\n}\n```\n:::\n\n\n###Regressão OLS\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Estimar modelo: Y = β0 + β1*Desonerado + β2*Post + β3*(Desonerado×Post) + ε\nmodelo <- lm(n_trabalhadores ~ desonerado + post + desoneracao, data = dados)\n```\n:::\n\n\n#### Interpretação dos Coeficientes\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Extrair coeficientes\nbeta_0 <- coef(modelo)[\"(Intercept)\"]\nbeta_1 <- coef(modelo)[\"desonerado\"]\nbeta_2 <- coef(modelo)[\"post\"]\nbeta_3 <- coef(modelo)[\"desoneracao\"]\n\ncat(\"\\n=== INTERPRETAÇÃO DOS COEFICIENTES ===\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n=== INTERPRETAÇÃO DOS COEFICIENTES ===\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"β₀ (Intercepto):         %.4f\\n\", beta_0))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nβ₀ (Intercepto):         110.1420\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"   → Emprego médio nos setores não desonerados antes de 2012\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   → Emprego médio nos setores não desonerados antes de 2012\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"β₁ (Desonerado):         %.4f\\n\", beta_1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nβ₁ (Desonerado):         31.5908\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"   → Diferença fixa entre setores (efeito fixo de grupo)\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   → Diferença fixa entre setores (efeito fixo de grupo)\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"β₂ (Post):               %.4f\\n\", beta_2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nβ₂ (Post):               22.1818\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"   → Tendência temporal comum (crescimento econômico)\\n\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   → Tendência temporal comum (crescimento econômico)\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(sprintf(\"β₃ (Desonerado × Post):  %.4f ***\\n\", beta_3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nβ₃ (Desonerado × Post):  25.2538 ***\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\ncat(\"   → EFEITO CAUSAL DA DESONERAÇÃO (DiD/ATT)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   → EFEITO CAUSAL DA DESONERAÇÃO (DiD/ATT)\n```\n:::\n:::\n\n\n### Visualização: Tendências Paralelas\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calcular médias por ano e grupo\nmedias_ano <- aggregate(n_trabalhadores ~ ano + desonerado, data = dados, FUN = mean)\n\n# Criar gráfico\npar(mar = c(5, 5, 4, 2))\n\n# Plotar setores não desonerados\nplot(medias_ano$ano[medias_ano$desonerado == 0], \n     medias_ano$n_trabalhadores[medias_ano$desonerado == 0],\n     type = \"b\", pch = 15, col = \"#e74c3c\", lwd = 3, cex = 1.5,\n     xlab = \"Ano\", ylab = \"Número de Trabalhadores\",\n     main = \"Impacto da Desoneração da Folha no Emprego\\nTendências Paralelas\",\n     ylim = range(medias_ano$n_trabalhadores),\n     cex.lab = 1.3, cex.main = 1.4, cex.axis = 1.2)\n\n# Adicionar setores desonerados\nlines(medias_ano$ano[medias_ano$desonerado == 1], \n      medias_ano$n_trabalhadores[medias_ano$desonerado == 1],\n      type = \"b\", pch = 16, col = \"#27ae60\", lwd = 3, cex = 1.5)\n\n# Linha vertical no ano da desoneração\nabline(v = ano_desoneracao - 0.5, col = \"gray\", lty = 2, lwd = 2.5)\n\n# Legenda\nlegend(\"topleft\", \n       legend = c(\"Setores Desonerados\", \"Setores Não Desonerados\"),\n       col = c(\"#27ae60\", \"#e74c3c\"), \n       pch = c(16, 15), \n       lwd = 3, \n       cex = 1.2,\n       bty = \"n\")\n\n# Anotação\ntext(ano_desoneracao - 0.5, max(medias_ano$n_trabalhadores) * 0.95, \n     \"Lei 12.546/2011\\nDesoneração (2012)\", \n     pos = 4, cex = 1.1, font = 2)\n\n# Grid\ngrid(col = \"gray\", lty = \"dotted\")\n```\n\n::: {.cell-output-display}\n![Tendências paralelas em dados simulados da desoneração da folha. As trajetórias são similares antes de 2012 e divergem após a implementação da política.](index_files/figure-html/grafico-tendencias-1.png){width=960}\n:::\n:::\n\n\n### Resultados\n\nO gráfico acima visualiza as tendências paralelas. Note como:\n\n1.  **Antes de 2012**: As linhas dos dois grupos são aproximadamente paralelas, validando visualmente nossa hipótese identificadora\n2.  **Após 2012**: A linha dos setores desonerados se afasta para cima, capturando o efeito positivo da política\n3.  **Magnitude**: O gap vertical entre as linhas após 2012 representa o efeito DiD de aproximadamente **+25 trabalhadores**\n\n**Tabela Resumo dos Resultados:**\n\n| Método             | Estimativa | Erro Padrão | Estatística t | p-valor  |\n|--------------------|------------|-------------|---------------|----------|\n| DiD Manual         | +25.25     | \\-          | \\-            | \\-       |\n| Regressão OLS (β₃) | +25.25     | 1.69        | 14.96         | \\< 0.001 |\n\n**Conclusão:** A desoneração da folha aumentou o emprego em aproximadamente **25 trabalhadores** nas empresas beneficiadas, controlando por tendências temporais comuns e diferenças fixas entre setores. O efeito é altamente significativo estatisticamente.\n\n## Two-Way Fixed Effects (TWFE)\n\nAté agora, trabalhamos com o caso mais simples do DiD: dois grupos (tratado e controle) e dois períodos (antes e depois). Mas o que acontece quando temos **múltiplos grupos tratados em diferentes momentos**? Por exemplo, se alguns setores foram desonerados em 2012, outros em 2013, e outros nunca foram desonerados?\n\nNesse cenário mais realista, é comum usar o estimador **Two-Way Fixed Effects (TWFE)**, que é simplesmente uma regressão com efeitos fixos de unidade e tempo:\n\n$$\nY_{it} = \\alpha_i + \\lambda_t + \\beta \\cdot D_{it} + \\varepsilon_{it}\n$$\n\nOnde $\\alpha_i$ são efeitos fixos de unidade, $\\lambda_t$ são efeitos fixos de tempo, e $D_{it}$ é o indicador de tratamento.\n\n**A grande questão:** O que exatamente o coeficiente $\\beta$ do TWFE está estimando quando há heterogeneidade no timing do tratamento?\n\nGoodman-Bacon (2021) provou um resultado matemático elegante e surpreendente:\n\n> **O estimador TWFE é uma média ponderada de todos os possíveis estimadores DD 2×2 que podem ser construídos com os dados.**\n\nFormalmente:\n\n$$\n\\hat{\\beta}^{DD} = \\sum_{k\\neq U} s_{kU} \\hat{\\beta}_{kU}^{2\\times2} + \\sum_{k\\neq U} \\sum_{\\ell > k} \\left[ s_{k\\ell}^k \\hat{\\beta}_{k\\ell}^{2\\times2,k} + s_{k\\ell}^\\ell \\hat{\\beta}_{k\\ell}^{2\\times2,\\ell} \\right]\n$$\n\nOnde:\n\n-   $\\hat{\\beta}_{kU}^{2\\times2}$: comparação entre grupo tratado ($k$) vs. nunca tratado ($U$)\n-   $\\hat{\\beta}_{k\\ell}^{2\\times2,k}$: comparação usando grupo $k$ (tratado precocemente) como tratamento e grupo $\\ell$ (tratado tardiamente) como controle\n-   $\\hat{\\beta}_{k\\ell}^{2\\times2,\\ell}$: comparação usando grupo $\\ell$ (tratado tardiamente) como tratamento e grupo $k$ (já tratado) como controle\n-   $s_{kU}, s_{k\\ell}^k, s_{k\\ell}^\\ell$: pesos que somam 1\n\n**Interpretação:** A decomposição tem três tipos de comparações:\n\n1.  **Tratados vs. Nunca tratados** ($\\hat{\\beta}_{kU}$): Cada grupo tratado comparado com o grupo nunca tratado\n2.  **Tratados precoces vs. Tratados tardios** ($\\hat{\\beta}_{k\\ell}^{k}$): Grupos tratados precocemente usando grupos ainda não tratados como controles\n3.  **Tratados tardios vs. Tratados precoces** ($\\hat{\\beta}_{k\\ell}^{\\ell}$): Grupos tratados tardiamente usando grupos **já tratados** como controles\n\n## Exemplo Numérico: Três Grupos, Seis Períodos\n\n[Visualizar exemplo em excel](exemplo_twfe.xlsx){target=\"_blank\"}\n\n**Nota sobre a fórmula:** No caso geral do artigo de Goodman-Bacon, pode haver múltiplos grupos tratados em diferentes momentos. A fórmula completa tem somatórios duplos para capturar todas as comparações possíveis entre pares de grupos. No nosso exemplo específico, temos apenas:\n\n-   1 grupo nunca tratado (U)\n-   2 grupos tratados (K em t=3, L em t=5)\n\nPortanto, a decomposição se simplifica para:\n\n$$\n\\hat{\\beta}^{DD} = s_{kU} \\hat{\\beta}_{kU}^{2\\times2} + s_{\\ell U} \\hat{\\beta}_{\\ell U}^{2\\times2} + s_{k\\ell}^k \\hat{\\beta}_{k\\ell}^{2\\times2,k} + s_{k\\ell}^\\ell \\hat{\\beta}_{k\\ell}^{2\\times2,\\ell}\n$$\n\nVamos ilustrar com dados concretos. Considere:\n\n-   **Grupo U**: Nunca tratado (2 unidades: U1, U2)\n-   **Grupo K**: Tratado em $t=3$ (2 unidades: K1, K2)\n-   **Grupo L**: Tratado em $t=5$ (2 unidades: L1, L2)\n\n### Estrutura dos Dados\n\n**Médias de** $Y_{it}$ por grupo e tempo:\n\n| Grupo        | t=1  | t=2  | t=3  | t=4  | t=5  | t=6  |\n|--------------|------|------|------|------|------|------|\n| U (Nunca)    | 12.0 | 14.0 | 15.0 | 19.0 | 20.0 | 23.0 |\n| K (Trat t=3) | 11.5 | 14.0 | 21.0 | 23.0 | 25.0 | 27.0 |\n| L (Trat t=5) | 11.5 | 14.0 | 16.0 | 18.0 | 28.0 | 30.0 |\n\n**Indicador de Tratamento** $D_{it}$:\n\n| Grupo | t=1 | t=2 | t=3 | t=4 | t=5 | t=6 |\n|-------|-----|-----|-----|-----|-----|-----|\n| U     | 0   | 0   | 0   | 0   | 0   | 0   |\n| K     | 0   | 0   | 1   | 1   | 1   | 1   |\n| L     | 0   | 0   | 0   | 0   | 1   | 1   |\n\n## Passo 1: Calcular os Estimadores DD 2×2\n\n### 1.1. Grupo K vs. Grupo U\n\n**Períodos:** PRE = $\\{1,2\\}$, POST = $\\{3,4,5,6\\}$\n\n**Médias:**\n\n$$\n\\begin{aligned}\n\\bar{Y}_{K,PRE} &= \\frac{11.5 + 14.0}{2} = 12.75 \\\\\n\\bar{Y}_{K,POST} &= \\frac{21.0 + 23.0 + 25.0 + 27.0}{4} = 24.0 \\\\\n\\bar{Y}_{U,PRE} &= \\frac{12.0 + 14.0}{2} = 13.0 \\\\\n\\bar{Y}_{U,POST} &= \\frac{15.0 + 19.0 + 20.0 + 23.0}{4} = 19.25\n\\end{aligned}\n$$\n\n**Diferenças temporais:**\n\n$$\n\\begin{aligned}\n\\Delta_K &= \\bar{Y}_{K,POST} - \\bar{Y}_{K,PRE} = 24.0 - 12.75 = 11.25 \\\\\n\\Delta_U &= \\bar{Y}_{U,POST} - \\bar{Y}_{U,PRE} = 19.25 - 13.0 = 6.25\n\\end{aligned}\n$$\n\n**Estimador DD 2×2:**\n\n$$\n\\hat{\\beta}_{kU}^{2\\times2} = \\Delta_K - \\Delta_U = 11.25 - 6.25 = 5.0\n$$\n\n### 1.2. Grupo L vs. Grupo U\n\n**Períodos:** PRE = $\\{1,2,3,4\\}$, POST = $\\{5,6\\}$\n\n**Médias:**\n\n$$\n\\begin{aligned}\n\\bar{Y}_{L,PRE} &= \\frac{11.5 + 14.0 + 16.0 + 18.0}{4} = 14.875 \\\\\n\\bar{Y}_{L,POST} &= \\frac{28.0 + 30.0}{2} = 29.0 \\\\\n\\bar{Y}_{U,PRE} &= \\frac{12.0 + 14.0 + 15.0 + 19.0}{4} = 15.0 \\\\\n\\bar{Y}_{U,POST} &= \\frac{20.0 + 23.0}{2} = 21.5\n\\end{aligned}\n$$\n\n**Estimador DD 2×2:**\n\n$$\n\\hat{\\beta}_{\\ell U}^{2\\times2} = (29.0 - 14.875) - (21.5 - 15.0) = 14.125 - 6.5 = 7.625\n$$\n\n### 1.3. Grupo K vs. Grupo L (K como tratamento)\n\n**Períodos:** PRE = $\\{1,2\\}$, MID = $\\{3,4\\}$\n\nNesta comparação, usamos o Grupo L (ainda não tratado) como controle para o Grupo K.\n\n**Médias:**\n\n$$\n\\begin{aligned}\n\\bar{Y}_{K,PRE} &= 12.75, \\quad \\bar{Y}_{K,MID} = \\frac{21.0 + 23.0}{2} = 22.0 \\\\\n\\bar{Y}_{L,PRE} &= 12.75, \\quad \\bar{Y}_{L,MID} = \\frac{16.0 + 18.0}{2} = 17.0\n\\end{aligned}\n$$\n\n**Estimador DD 2×2:**\n\n$$\n\\hat{\\beta}_{k\\ell}^{k} = (22.0 - 12.75) - (17.0 - 12.75) = 9.25 - 4.25 = 5.0\n$$\n\n### 1.4. Grupo L vs. Grupo K (L como tratamento)\n\n**Períodos:** MID = $\\{3,4\\}$, POST = $\\{5,6\\}$\n\n**ATENÇÃO:** Nesta comparação, usamos o Grupo K **já tratado** como controle para o Grupo L. Isso pode ser problemático se o efeito do tratamento em K estiver evoluindo ao longo do tempo.\n\n**Médias:**\n\n$$\n\\begin{aligned}\n\\bar{Y}_{L,MID} &= 17.0, \\quad \\bar{Y}_{L,POST} = 29.0 \\\\\n\\bar{Y}_{K,MID} &= 22.0, \\quad \\bar{Y}_{K,POST} = \\frac{25.0 + 27.0}{2} = 26.0\n\\end{aligned}\n$$\n\n**Estimador DD 2×2:**\n\n$$\n\\hat{\\beta}_{k\\ell}^{\\ell} = (29.0 - 17.0) - (26.0 - 22.0) = 12.0 - 4.0 = 8.0\n$$\n\n### Resumo dos Estimadores 2×2\n\n| Comparação                 | Estimador | Interpretação             |\n|----------------------------|-----------|---------------------------|\n| $\\hat{\\beta}_{kU}$         | 5.0       | K vs. Nunca tratado       |\n| $\\hat{\\beta}_{\\ell U}$     | 7.625     | L vs. Nunca tratado       |\n| $\\hat{\\beta}_{k\\ell}^k$    | 5.0       | K vs. L (L como controle) |\n| $\\hat{\\beta}_{k\\ell}^\\ell$ | 8.0       | L vs. K (K como controle) |\n\n## Passo 2: Calcular os Pesos\n\nOs pesos na decomposição de Goodman-Bacon dependem de:\n\n1.  **Tamanho relativo dos grupos** na comparação\n2.  **Variância do tratamento** dentro da comparação\n\n### Fórmulas dos Pesos\n\nPara uma comparação entre grupos $g$ e $h$:\n\n$$\ns_{gh} = \\frac{w_{gh}}{\\sum w}\n$$\n\nOnde o peso não normalizado é:\n\n$$\nw_{gh} = n_{gh}^2 \\cdot V_{D,gh}\n$$\n\n-   $n_{gh}$: proporção da amostra na comparação\n-   $V_{D,gh}$: variância do tratamento na comparação\n\n### Cálculo para Nosso Exemplo\n\n**Proporções dos grupos:**\n\n$$\nn_U = n_K = n_L = \\frac{2}{6} = \\frac{1}{3}\n$$\n\n**Proporção de períodos tratados:**\n\n$$\n\\bar{D}_K = \\frac{4}{6} = \\frac{2}{3}, \\quad \\bar{D}_L = \\frac{2}{6} = \\frac{1}{3}\n$$\n\n**Para comparações com grupo nunca tratado:**\n\n$$\n\\begin{aligned}\n\\mu_{kU} &= \\frac{n_K}{n_K + n_U} = \\frac{1/3}{2/3} = 0.5 \\\\\nV_{kU} &= \\mu_{kU}(1 - \\mu_{kU}) \\bar{D}_K (1 - \\bar{D}_K) = 0.5 \\times 0.5 \\times \\frac{2}{3} \\times \\frac{1}{3} = \\frac{1}{18} \\\\\nw_{kU} &= \\left(\\frac{2}{3}\\right)^2 \\times \\frac{1}{18} = \\frac{4}{9} \\times \\frac{1}{18} = \\frac{1}{40.5}\n\\end{aligned}\n$$\n\nSimilarmente, $w_{\\ell U} = \\frac{1}{40.5}$.\n\n**Para comparações entre grupos tratados:**\n\n$$\n\\begin{aligned}\nV_{k\\ell}^k &= \\mu_{k\\ell}(1 - \\mu_{k\\ell}) \\frac{\\bar{D}_K - \\bar{D}_L}{1 - \\bar{D}_L} \\frac{1 - \\bar{D}_K}{1 - \\bar{D}_L} \\\\\n&= 0.5 \\times 0.5 \\times \\frac{1/3}{2/3} \\times \\frac{1/3}{2/3} = 0.25 \\times 0.5 \\times 0.5 = \\frac{1}{16}\n\\end{aligned}\n$$\n\n$$\nw_{k\\ell}^k = \\left[\\left(\\frac{2}{3}\\right) \\times \\frac{2}{3}\\right]^2 \\times \\frac{1}{16} = \\left(\\frac{4}{9}\\right)^2 \\times \\frac{1}{16} = \\frac{1}{81}\n$$\n\nSimilarmente, $w_{k\\ell}^\\ell = \\frac{1}{81}$.\n\n### Pesos Normalizados\n\n$$\n\\sum w = \\frac{1}{40.5} + \\frac{1}{40.5} + \\frac{1}{81} + \\frac{1}{81} \\approx 0.0741\n$$\n\n$$\n\\begin{aligned}\ns_{kU} &= \\frac{1}{3} \\approx 0.3333 \\\\\ns_{\\ell U} &= \\frac{1}{3} \\approx 0.3333 \\\\\ns_{k\\ell}^k &= \\frac{1}{6} \\approx 0.1667 \\\\\ns_{k\\ell}^\\ell &= \\frac{1}{6} \\approx 0.1667\n\\end{aligned}\n$$\n\n**Verificação:** $\\frac{1}{3} + \\frac{1}{3} + \\frac{1}{6} + \\frac{1}{6} = 1$\n\n## Passo 3: Decomposição de Goodman-Bacon\n\nAgora calculamos a média ponderada dos estimadores DD 2×2:\n\n$$\n\\begin{aligned}\n\\hat{\\beta}^{DD} &= s_{kU} \\hat{\\beta}_{kU} + s_{\\ell U} \\hat{\\beta}_{\\ell U} + s_{k\\ell}^k \\hat{\\beta}_{k\\ell}^k + s_{k\\ell}^\\ell \\hat{\\beta}_{k\\ell}^\\ell \\\\\n&= \\frac{1}{3} \\times 5.0 + \\frac{1}{3} \\times 7.625 + \\frac{1}{6} \\times 5.0 + \\frac{1}{6} \\times 8.0 \\\\\n&= 1.667 + 2.542 + 0.833 + 1.333 \\\\\n&= 6.375\n\\end{aligned}\n$$\n\n### Tabela de Decomposição\n\n| Comparação | Estimador | Peso | Contribuição |\n|------------------|------------------|------------------|------------------|\n| $\\hat{\\beta}_{kU} \\times s_{kU}$ | 5.000 | 0.3333 | 1.667 |\n| $\\hat{\\beta}_{\\ell U} \\times s_{\\ell U}$ | 7.625 | 0.3333 | 2.542 |\n| $\\hat{\\beta}_{k\\ell}^k \\times s_{k\\ell}^k$ | 5.000 | 0.1667 | 0.833 |\n| $\\hat{\\beta}_{k\\ell}^\\ell \\times s_{k\\ell}^\\ell$ | 8.000 | 0.1667 | 1.333 |\n| **Total** |  | **1.0000** | **6.375** |\n\n## Passo 4: Verificação com Regressão TWFE\n\nRodando a regressão:\n\n$$\nY_{it} = \\alpha_i + \\lambda_t + \\beta \\cdot D_{it} + \\varepsilon_{it}\n$$\n\nObtemos: $\\hat{\\beta}^{TWFE} = 6.375$\n\n**Os valores batem**\n\nIsso confirma o teorema de Goodman-Bacon: o estimador TWFE é exatamente a média ponderada dos estimadores DD 2×2.\n\n## Implicações Práticas\n\n### 1. Interpretação do Coeficiente TWFE\n\nO coeficiente $\\hat{\\beta}^{TWFE} = 6.375$ **não é simplesmente a média dos efeitos do tratamento**. É uma **média ponderada complexa** que depende de:\n\n-   Timing do tratamento (quando cada grupo foi tratado)\n-   Tamanho dos grupos\n-   Variância do tratamento\n\n### 2. O Problema das Comparações \"Contaminadas\"\n\nObserve que $\\hat{\\beta}_{k\\ell}^\\ell = 8.0$ usa o **Grupo K já tratado** como controle para o Grupo L.\n\n**Por que isso é problemático?**\n\nSe o efeito do tratamento no Grupo K estiver **evoluindo ao longo do tempo** (efeitos dinâmicos), a diferença temporal de K ($\\Delta_K = \\bar{Y}_{K,POST} - \\bar{Y}_{K,MID}$) inclui:\n\n1.  Tendência temporal comum (que queremos remover)\n2.  **Mudança no efeito do tratamento** (que contamina a estimativa)\n\n### 3. Quando o TWFE Funciona Bem\n\nO TWFE identifica corretamente o efeito causal médio quando:\n\n1.  **Efeitos homogêneos:** Todos os grupos têm o mesmo efeito ($\\tau_K = \\tau_L$)\n2.  **Sem efeitos dinâmicos:** O efeito não muda ao longo do tempo ($\\tau_{it} = \\tau$)\n3.  **Tendências paralelas:** Válidas para todas as comparações 2×2\n\n### 4. Quando o TWFE Falha\n\nO TWFE pode dar estimativas **enviesadas** quando:\n\n1.  **Efeitos heterogêneos:** Diferentes grupos têm efeitos diferentes\n2.  **Efeitos dinâmicos:** O efeito do tratamento evolui ao longo do tempo\n3.  **Pesos negativos:** Em casos extremos, alguns pesos $s$ podem ser negativos!\n\n## Soluções Alternativas\n\nQuando há heterogeneidade no timing e nos efeitos, considere: **Callaway & Sant'Anna (2021)** e **Wooldrigde (2021)-ETWFE**\n\nA decomposição de Goodman-Bacon revela que o estimador TWFE, aparentemente simples, esconde uma complexidade considerável quando há múltiplos grupos tratados em diferentes momentos.\n\n**Principais lições:**\n\n1.  TWFE = média ponderada de comparações DD 2×2\n\n2.  Algumas comparações usam grupos já tratados como controles\n\n3.  Com efeitos heterogêneos ou dinâmicos, TWFE pode ser enviesado\n\n## Event Studies: Testando Tendências Paralelas e Efeitos Dinâmicos\n\n### Da Estimativa Única aos Efeitos Dinâmicos\n\nAté agora, estimamos um **único efeito médio** da desoneração: +25 trabalhadores. Mas essa abordagem esconde informações importantes:\n\n1.  **O efeito foi imediato ou gradual?**\n2.  **O efeito cresceu ou diminuiu ao longo do tempo?**\n3.  **Mais importante: as tendências eram realmente paralelas antes de 2012?**\n\nO **Event Study** (ou estudo de eventos) responde a essas perguntas estimando um **efeito separado para cada ano** relativo ao tratamento.\n\n### A Especificação de Regressão do Event Study\n\nEm vez de uma única dummy `Post`, criamos **dummies para cada ano** relativo ao tratamento:\n\n$$Y_{it} = \\alpha_i + \\lambda_t + \\sum_{k \\neq -1} \\beta_k \\cdot \\mathbb{1}\\{\\text{Tempo Relativo}_{it} = k\\} \\cdot D_i + \\varepsilon_{it}$$\n\nOnde: - $\\text{Tempo Relativo}_{it} = t - 2012$ (anos relativos à desoneração) - $k \\in \\{-5, -4, -3, -2, -1, 0, 1, 2, 3\\}$ são os anos relativos - $\\beta_k$ são os **coeficientes de interesse** (efeito no ano $k$) - **Normalização:** Omitimos $k = -1$ como período de referência\n\n### Interpretação dos Parâmetros Temporais\n\n**Coeficientes Pré-Tratamento (**$\\beta_k$ para $k < 0$):\n\n-   Capturam diferenças nas tendências *antes* da política\n-   **Devem ser ≈ 0** se as tendências forem paralelas\n-   Se $\\beta_k \\neq 0$: evidência de violação de tendências paralelas\n\n**Coeficientes Pós-Tratamento (**$\\beta_k$ para $k \\geq 0$):\n\n-   Capturam o efeito causal dinâmico da desoneração\n-   $\\beta_0$: efeito imediato (2012)\n-   $\\beta_1, \\beta_2, \\beta_3$: efeitos subsequentes\n\n### Por que Event Studies Testam Tendências Paralelas?\n\nA hipótese de tendências paralelas **não pode ser testada diretamente** (o contrafactual é inobservável). Mas podemos fazer um **teste indireto**:\n\n-   **Se as tendências eram paralelas antes**, é plausível que continuariam paralelas na ausência do tratamento\n-   **Se as tendências divergiam antes**, não há razão para acreditar que convergiriam após 2012\n-   **Event study revela essas tendências** através dos coeficientes pré-tratamento\n\n**Teste Visual:** Plotar $\\beta_k$ com intervalos de confiança e verificar se $\\beta_k \\approx 0$ para $k < 0$.\n\n### Implementação com Dados Simulados\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(fixest)\n# Criar variável de tempo relativo\ndados <- dados %>%\n  mutate(tempo_relativo = ano - ano_desoneracao)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodelo_event <- feols(\n  n_trabalhadores ~ i(tempo_relativo, desonerado, ref = -1) | \n                    empresa_id + ano,\n  data = dados,\n  cluster = ~empresa_id  # Erros padrão clusterizados\n)\n\n# Extrair resultados\nresultados_event <- broom::tidy(modelo_event, conf.int = TRUE)\n\n# Ou visualizar diretamente\niplot(modelo_event ,\n      main = \"Event Study: Desoneração da Folha\",\n      xlab = \"Tempo Relativo\",\n      ylab = \"Efeito no Emprego\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/event-regressao-1.png){width=672}\n:::\n:::\n\n\n### O que o Gráfico Revela?\n\n| Coeficiente | Notação | Interpretação |\n|------------------------|------------------------|------------------------|\n| **β₋₅** | `tempo_relativo = -5` | Diferença no emprego entre setores desonerados e não desonerados **5 anos antes** da política (2007 vs 2007), controlando por FEs de empresa e tempo. |\n| **β₋₄** | `tempo_relativo = -4` | Diferença no emprego entre setores desonerados e não desonerados **4 anos antes** da política (2008 vs 2008), controlando por FEs. |\n| **β₋₃** | `tempo_relativo = -3` | Diferença no emprego entre setores desonerados e não desonerados **3 anos antes** da política (2009 vs 2009), controlando por FEs. |\n| **β₋₂** | `tempo_relativo = -2` | Diferença no emprego entre setores desonerados e não desonerados **2 anos antes** da política (2010 vs 2010), controlando por FEs. |\n| **β₋₁** | `tempo_relativo = -1` | **PERÍODO DE REFERÊNCIA** (omitido)<br/>Normalizado em zero por construção (2011). |\n| **β₀** | `tempo_relativo = 0` | **Efeito causal imediato** da desoneração no ano de implementação (2012).<br/>Mudança no emprego dos setores desonerados **relativa** aos não desonerados, comparado com 2011. |\n| **β₁** | `tempo_relativo = 1` | **Efeito causal 1 ano após** a desoneração (2013).<br/>Acúmulo do efeito da política após 1 ano. |\n| **β₂** | `tempo_relativo = 2` | **Efeito causal 2 anos após** a desoneração (2014).<br/>Acúmulo do efeito da política após 2 anos. |\n| **β₃** | `tempo_relativo = 3` | **Efeito causal 3 anos após** a desoneração (2015).<br/>Efeito de longo prazo da política. |\n\n### Notas Importantes\n\n**Interpretação Formal dos Coeficientes:**\n\nPara qualquer tempo relativo *k*, o coeficiente β_k representa:\n\n$$\n\\beta_k = E[Y_{it} | \\text{Desonerado}_i = 1, \\text{TempoRelativo}_{it} = k] - E[Y_{it} | \\text{Desonerado}_i = 0, \\text{TempoRelativo}_{it} = k]\n$$\n\nControlando por efeitos fixos de empresa (α_i) e efeitos fixos de tempo (λ_t).\n\n**Em palavras simples:** \\> β_k mede a diferença no número de trabalhadores entre setores desonerados e não desonerados no período *k* relativo à desoneração, **comparado com a diferença no período de referência** (k = -1).\n\n**Condições para Identificação Causal:**\n\n1.  **Tendências Paralelas (Pré-Tratamento):**\n    -   β₋₅, β₋₄, β₋₃, β₋₂ devem ser estatisticamente indistinguíveis de zero\n    -   Se todos ≈ 0: forte evidência de que setores desonerados e não desonerados teriam evoluído de forma paralela na ausência da política\n2.  **Ausência de Antecipação:**\n    -   Coeficientes pré-tratamento não devem mostrar \"salto\" antes de 2012\n    -   Empresas não devem ter ajustado emprego em antecipação à política\n3.  **Efeito Causal (Pós-Tratamento):**\n    -   β₀, β₁, β₂, β₃ \\> 0: a desoneração aumentou o emprego\n    -   Se β₀ \\< β₁ \\< β₂: efeito crescente (ajuste gradual)\n    -   Se β₀ ≈ β₁ ≈ β₂: efeito imediato e constante\n\n## ETWFE: tratamento Escalonada\n\nNo exemplo que acabamos de ver, todos os setores desonerados receberam o tratamento **simultaneamente** em 2012. Nesse caso, o TWFE tradicional funciona perfeitamente e produz estimativas não enviesadas do ATT.\n\nMas e se a realidade fosse mais complexa? E se a desoneração tivesse sido implementada de forma **escalonada**, com diferentes setores sendo desonerados em anos diferentes?\n\n## Simulando Desoneração Escalonada\n\nVamos modificar nossos dados para criar um cenário mais realista de **tratamento escalonado** (staggered treatment):\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Usar mesma estrutura de simulação, mas com tratamento escalonado\nset.seed(42)\n\n# Parâmetros (mesmos do exemplo anterior)\nn_empresas <- 100\nn_anos <- 9\nano_inicio <- 2007\n\n# Criar data frame\ndados_esc <- data.frame()\n\nfor (i in 1:n_empresas) {\n  # Dividir empresas em 3 grupos\n  if (i <= 33) {\n    # Grupo K: desonerados em 2012\n    coorte <- 2012\n    desonerado <- 1\n  } else if (i <= 66) {\n    # Grupo L: desonerados em 2014\n    coorte <- 2014\n    desonerado <- 1\n  } else {\n    # Grupo U: nunca desonerados\n    coorte <- 0\n    desonerado <- 0\n  }\n  \n  # Efeito fixo da empresa (mesmo do exemplo anterior)\n  efeito_fixo <- 100 + (30 * desonerado) + rnorm(1, mean = 0, sd = 10)\n  \n  for (t in 0:(n_anos - 1)) {\n    ano <- ano_inicio + t\n    \n    # Tendência temporal comum (mesma do exemplo anterior)\n    tendencia_temporal <- 5 * t\n    \n    # Efeito da desoneração (agora depende da coorte)\n    if (coorte == 2012 & ano >= 2012) {\n      # Grupo K: efeito de 25 trabalhadores\n      efeito_desoneracao <- 25\n    } else if (coorte == 2014 & ano >= 2014) {\n      # Grupo L: efeito de 20 trabalhadores (ligeiramente menor)\n      efeito_desoneracao <- 20\n    } else {\n      efeito_desoneracao <- 0\n    }\n    \n    # Ruído aleatório\n    erro <- rnorm(1, mean = 0, sd = 5)\n    \n    # Número de trabalhadores\n    n_trabalhadores <- efeito_fixo + tendencia_temporal + efeito_desoneracao + erro\n    \n    # Criar variável de tratamento\n    tratado <- ifelse((coorte == 2012 & ano >= 2012) | (coorte == 2014 & ano >= 2014), 1, 0)\n    \n    # Adicionar linha\n    dados_esc <- rbind(dados_esc, data.frame(\n      empresa_id = i,\n      ano = ano,\n      coorte = coorte,\n      tratado = tratado,\n      n_trabalhadores = n_trabalhadores\n    ))\n  }\n}\n\n# Visualizar trajetórias\nlibrary(dplyr)\nlibrary(ggplot2)\n\nmedias_esc <- dados_esc %>%\n  mutate(grupo = case_when(\n    coorte == 2012 ~ \"K (Deson. 2012)\",\n    coorte == 2014 ~ \"L (Deson. 2014)\",\n    coorte == 0 ~ \"U (Nunca)\"\n  )) %>%\n  group_by(ano, grupo) %>%\n  summarise(n_trab_medio = mean(n_trabalhadores), .groups = \"drop\")\n\nggplot(medias_esc, aes(x = ano, y = n_trab_medio, color = grupo, group = grupo)) +\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 3) +\n  geom_vline(xintercept = 2011.5, linetype = \"dashed\", color = \"red\", alpha = 0.5) +\n  geom_vline(xintercept = 2013.5, linetype = \"dashed\", color = \"orange\", alpha = 0.5) +\n  annotate(\"text\", x = 2012, y = max(medias_esc$n_trab_medio), \n           label = \"K desonerado\", vjust = -0.5, color = \"red\", size = 3.5) +\n  annotate(\"text\", x = 2014, y = max(medias_esc$n_trab_medio), \n           label = \"L desonerado\", vjust = -1.5, color = \"orange\", size = 3.5) +\n  scale_color_manual(values = c(\"K (Deson. 2012)\" = \"#27ae60\", \n                                 \"L (Deson. 2014)\" = \"#3498db\",\n                                 \"U (Nunca)\" = \"#e74c3c\")) +\n  labs(title = \"Desoneração Escalonada: Trajetórias de Emprego por Coorte\",\n       subtitle = \"Grupo K desonerado em 2012, Grupo L em 2014, Grupo U nunca desonerado\",\n       x = \"Ano\", y = \"Número Médio de Trabalhadores\", color = \"Grupo\") +\n  theme_minimal() +\n  theme(legend.position = \"bottom\",\n        plot.title = element_text(face = \"bold\"))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/dados-escalonados-1.png){width=672}\n:::\n:::\n\n\n## O Problema do TWFE com Tratamento Escalonado\n\nVamos estimar o TWFE tradicional nesses dados:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(fixest)\n\n# TWFE tradicional\nmod_twfe <- feols(n_trabalhadores ~ tratado | empresa_id + ano, \n                  data = dados_esc,\n                  vcov = ~empresa_id)\n\n# Resultado\nsummary(mod_twfe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOLS estimation, Dep. Var.: n_trabalhadores\nObservations: 900\nFixed-effects: empresa_id: 100,  ano: 9\nStandard-errors: Clustered (empresa_id) \n        Estimate Std. Error t value  Pr(>|t|)    \ntratado  23.0884   0.656958 35.1444 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 4.80258     Adj. R2: 0.969085\n                Within R2: 0.603727\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# Extrair ATT\natt_twfe <- coef(mod_twfe)[\"tratado\"]\ncat(sprintf(\"\\nATT estimado pelo TWFE: %.2f trabalhadores\\n\", att_twfe))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nATT estimado pelo TWFE: 23.09 trabalhadores\n```\n:::\n:::\n\n\n**Problema:** O coeficiente do TWFE é uma **média ponderada** de várias comparações DD 2×2, incluindo:\n\n1.  Grupo K vs. Grupo U\n2.  Grupo L vs. Grupo U\n3.  Grupo K vs. Grupo L (quando L ainda não tratado)\n4.  **Grupo L vs. Grupo K (quando K já tratado)** (problemático!)\n\nA última comparação usa o Grupo K **já desonerado** como controle para o Grupo L. Se o efeito no Grupo K estiver evoluindo, essa comparação fica contaminada e o TWFE pode ser enviesado. Em outras palavras, se o ATT variar no tempo teremos problemas.\n\n## A Solução: ETWFE (Extended TWFE)\n\nWooldridge (2021, 2023) propôs **saturar o modelo** com todas as interações possíveis entre tratamento, coorte e tempo:\n\n$$\nY_{it} = \\alpha_i + \\lambda_t + \\sum_{g \\neq U} \\sum_{t} \\beta_{gt} \\cdot \\mathbb{1}[G_i = g] \\cdot \\mathbb{1}[T = t] \\cdot D_{it} + \\varepsilon_{it}\n$$\n\nOnde: - $G_i$: coorte da empresa $i$ (ano em que foi desonerada) - $\\beta_{gt}$: efeito da desoneração para coorte $g$ no ano $t$ - $D_{it} = 1$ se empresa $i$ está desonerada no ano $t$\n\n**Intuição:** Cada coorte × ano tem seu próprio coeficiente, permitindo heterogeneidade total nos efeitos.\n\n### Estimando o ETWFE\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\nlibrary(etwfe)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: pacote 'etwfe' foi compilado no R versão 4.4.3\n```\n:::\n\n```{.r .cell-code  code-fold=\"false\"}\n# Estimar ETWFE\nmod_etwfe <- etwfe(\n  fml  = n_trabalhadores ~ 1,  # sem controles\n  tvar = ano,                   # variável de tempo\n  gvar = coorte,                # variável de coorte\n  data = dados_esc,             # dataset\n  vcov = ~empresa_id            # erros clusterizados\n)\nresultados_etwfe <- broom::tidy(mod_etwfe, conf.int = TRUE)\n\n# Ver resumo\nsummary(mod_etwfe)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nOLS estimation, Dep. Var.: n_trabalhadores\nObservations: 900\nFixed-effects: coorte: 3,  ano: 9\nStandard-errors: Clustered (empresa_id) \n                               Estimate Std. Error t value  Pr(>|t|)    \n.Dtreat:coorte::2012:ano::2012  25.6121    1.04419 24.5281 < 2.2e-16 ***\n.Dtreat:coorte::2012:ano::2013  24.8691    1.19296 20.8465 < 2.2e-16 ***\n.Dtreat:coorte::2012:ano::2014  22.6393    1.41846 15.9605 < 2.2e-16 ***\n.Dtreat:coorte::2012:ano::2015  24.5765    1.44198 17.0436 < 2.2e-16 ***\n.Dtreat:coorte::2014:ano::2014  19.9948    1.31612 15.1922 < 2.2e-16 ***\n.Dtreat:coorte::2014:ano::2015  20.1489    1.59112 12.6634 < 2.2e-16 ***\n... 10 variables were removed because of collinearity (.Dtreat:coorte::2012:ano::2008, .Dtreat:coorte::2012:ano::2009 and 8 others [full set in $collin.var])\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\nRMSE: 10.7     Adj. R2: 0.863225\n             Within R2: 0.238559\n```\n:::\n:::\n\n\n**O que aconteceu?**\n\nO `etwfe()` criou automaticamente todas as interações: - `.Dtreat × coorte::2012 × ano::2012` - `.Dtreat × coorte::2012 × ano::2013` - ... (e assim por diante para todas as combinações)\n\nOs coeficientes brutos do modelo ETWFE **não são** o ATT\n\n### Efeitos Marginais (ATT Interpretável)\n\nPara obter o ATT, precisamos **agregar** os coeficientes brutos:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Calcular ATT médio\natt_etwfe <- emfx(mod_etwfe, type = \"simple\")\natt_etwfe\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n .Dtreat Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %\n    TRUE       23      0.688 33.4   <0.001 810.4  21.6   24.3\n\nTerm: .Dtreat\nType:  response \nComparison: TRUE - FALSE\n```\n:::\n:::\n\n\n**O que é o ATT médio?**\n\nÉ a **média ponderada** de todos os efeitos $\\beta_{gt}$ para as observações tratadas:\n\n$$\n\\widehat{ATT}_{\\text{simple}} = \\frac{1}{N_{\\text{tratado}}} \\sum_{i=1}^{N} \\sum_{t=1}^{T} \\mathbb{1}[D_{it} = 1] \\cdot \\hat{\\beta}_{G_i, t}\n$$ - $N$: número total de unidades\n\n-   $T$: número total de períodos\n\n-   $D_{it} = 1$: indicador de que a unidade $i$ está tratada no tempo $t$\n\n-   $G_i$: coorte da unidade $i$ (ano em que foi tratada pela primeira vez)\n\n-   $\\hat{\\beta}_{G_i, t}$: coeficiente estimado para a coorte $G_i$ no tempo $t$\n\n-   $N_{\\text{tratado}} = \\sum_{i,t} \\mathbb{1}[D_{it} = 1]$: número total de observações tratadas\n\n## Efeitos Dinâmicos (Event Study)\n\nO mais interessante é ver como o efeito **evolui ao longo do tempo**:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Event study: efeitos por tempo relativo\nemfx_event <- emfx(mod_etwfe, type = \"event\")\nplot(emfx_event ,\n      main = \"Event Study: Desoneração da Folha\",\n      xlab = \"Tempo Relativo\",\n      ylab = \"Efeito no Emprego\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/event-study-etwfe-esc-1.png){width=672}\n:::\n:::\n\n\nObserve que `emfx` apenas relata efeitos pós-tratamento aqui. Isso ocorre porque todos os efeitos pré-tratamento foram eliminados da estimação em decorrência da configuração ETWFE. Especificamente, no padrão em que o grupo de controle é composto pelas unidades “ainda não” tratadas, todos os efeitos pré-tratamento são definidos mecanicamente como zero. Alternativamente, é possível especificar as unidades “nunca” tratadas como grupo de controle chamando etwfe(..., cgroup = \"never\"). Essa opção retorna efeitos pré-tratamento, embora com o possível custo de estimativas menos precisas por não utilizar todas as informações disponíveis.\n\n-   `event = -2`: 2 anos **antes** da desoneração → deve ser ≈ 0 (tendências paralelas)\n-   `event = -1`: 1 ano antes → deve ser ≈ 0\n-   `event = 0`: Ano da desoneração → primeiro efeito\n-   `event = 1`: 1 ano após → efeito pode ter crescido\n-   `event = 2`: 2 anos após → efeito pode ter crescido mais\n\n**Como é calculado?**\n\nPara cada tempo relativo $j$:\n\n$$\n\\widehat{ATT}_j = \\frac{1}{N_j} \\sum_{i=1}^{N} \\sum_{t=1}^{T} \\mathbb{1}[D_{it} = 1] \\cdot \\mathbb{1}[t - G_i = j] \\cdot \\hat{\\beta}_{G_i, t}\n$$\n\n-   $j$: tempo relativo ao tratamento (ex: $j = -2, -1, 0, 1, 2, \\ldots$)\n\n-   $t - G_i$: anos desde que a unidade $i$ foi tratada\n\n-   $\\mathbb{1}[t - G_i = j]$: indicador de que estamos exatamente $j$ anos após o tratamento\n\n-   $N_j = \\sum_{i,t} \\mathbb{1}[D_{it} = 1] \\cdot \\mathbb{1}[t - G_i = j]$: número de observações no tempo relativo $j$\n\n## Efeitos por Coorte\n\nPodemos também ver o efeito **para cada coorte**:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"false\"}\n# Efeitos por coorte\nemfx_coorte <- emfx(mod_etwfe, type = \"group\")\nemfx_coorte\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n coorte Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %\n   2012     24.4      0.696 35.1   <0.001 894.9  23.1   25.8\n   2014     20.1      1.057 19.0   <0.001 264.7  18.0   22.1\n\nTerm: .Dtreat\nType:  response \nComparison: TRUE - FALSE\n```\n:::\n:::\n\n\n**Como é calculado?** \n$$\n\\widehat{ATT}_g = \\frac{1}{N_g} \\sum_{i=1}^{N} \\sum_{t=1}^{T} \\mathbb{1}[G_i = g] \\cdot \\mathbb{1}[D_{it} = 1] \\cdot \\hat{\\beta}_{g, t}\n$$\n\n-   $g$: coorte específica (ex: $g = 2012$ ou $g = 2014$)\n\n-   $\\mathbb{1}[G_i = g]$: indicador de que a unidade $i$ pertence à coorte $g$\n\n-   $N_g = \\sum_{i,t} \\mathbb{1}[G_i = g] \\cdot \\mathbb{1}[D_{it} = 1]$: número de observações tratadas da coorte $g$\n\n-   **Coorte K (2012):** ATT médio de \\~25 trabalhadores\n\n-   **Coorte L (2014):** ATT médio de \\~20 trabalhadores\n\nIsso confirma **heterogeneidade** entre coortes: setores desonerados em 2012 tiveram efeito ligeiramente maior (25) do que os desonerados em 2014 (20).\n\n## Resumo: Coeficientes Brutos vs. Efeitos Marginais\n\n| Conceito | O Que É | Interpretação | Uso |\n|------------------|------------------|------------------|------------------|\n| **Coeficientes Brutos** ($\\hat{\\beta}_{gt}$) | Parâmetros da regressão ETWFE | Efeito condicional para coorte $g$ no tempo $t$ | Não diretamente interpretável |\n| **ATT Simples** | `emfx(type = \"simple\")` | Média de todos $\\hat{\\beta}_{gt}$ tratados | Efeito médio geral |\n| **ATT por Tempo Relativo** | `emfx(type = \"event\")` | Média de $\\hat{\\beta}_{gt}$ para cada $j$ | Event study (efeitos dinâmicos) |\n| **ATT por Coorte** | `emfx(type = \"group\")` | Média de $\\hat{\\beta}_{gt}$ para cada coorte | Heterogeneidade entre grupos |\n\n## Triplas Diferenças (DDD)\n\nAté agora, exploramos como o Diferenças em Diferenças (DiD) pode isolar o efeito causal de uma política sob a hipótese crucial de **tendências paralelas**.\n\nE se o nosso grupo de controle, por alguma razão não observada, tiver uma trajetória de crescimento diferente do grupo de tratamento, mesmo na ausência da política?\n\nO método de **Triplas Diferenças (DDD)** é uma extensão do DiD que adiciona uma camada extra de controle, permitindo-nos obter estimativas causais mesmo quando a hipótese de tendências paralelas do DiD tradicional não se sustenta.\n\n### A Motivação: Quando o DiD Falha\n\nVamos revisitar nosso exemplo da desoneração da folha de pagamento. Nossa análise DiD comparou os setores desonerados (tratamento) com os setores não desonerados (controle). A validade do nosso resultado depende da suposição de que, se a desoneração não tivesse ocorrido, o emprego em ambos os grupos teria seguido a mesma tendência.\n\nA verdade é que o critério para ser contemplado pela política foi: pertencer ao setor desonerado e não ser optante do simples nacional.\n\nAgora imagine a seguinte situação:\n\nDe maneira resumida: a tendência não é paralela para as empresas dos setores desonerados e não desonerados, mas é paralela para para os setores desonerados e não desonerados que não estão sob o regime de tributação do Simples Nacional.\n\n## A Intuição do DDD\n\nA ideia é aplicar o DiD duas vezes:\n\n1.  **Primeiro DiD:** Calculamos o DiD para um critério: setores.\n\n2.  **Segundo DiD:** Calculamos um segundo DiD para o outro critério: regime de tributação\n\n3.  **Terceira Diferença:** Subtraímos o segundo DiD do primeiro DiD.\n\n## Decompondo o DDD: Um Exemplo Prático\n\nPara solidificar a intuição, vamos usar os dados do arquivo `ddd_exemplo.xlsx`.\n\nO estimador de Triplas Diferenças é **3.22**. Este é o nosso efeito causal final, ajustado para as tendências divergentes entre os grupos de tratamento e controle.\n\n## O Modelo de Regressão DDD\n\nAssim como no DiD, podemos estimar o DDD de forma mais robusta através de uma regressão OLS. O modelo requer a inclusão de uma interação tripla:\n\n$$ Y_{ist} = \\beta_0 + \\beta_1 T_i + \\beta_2 P_t + \\beta_3 S_i + \\beta_4 (T_i \\times P_t) + \\beta_5 (T_i \\times S_i) + \\beta_6 (P_t \\times S_i) + \\beta_7 (T_i \\times P_t \\times S_i) + \\varepsilon_{it} $$ Onde:\n\n-   $Y_{it}$ é a variável de resultado para a empresa $i$ no período $t$.\n\n-   $T_{i}$ é uma dummy para o **Não simples (alvo)**.\n\n-   $P_{t}$ é uma dummy para o período **Pós-tratamento**.\n\n-   $S_{i}$ é uma dummy para o grupo **Tratados**.\n\n**Interpretação dos Coeficientes:**\n\n-   As dummies individuais ($\\beta_1, \\beta_2, \\beta_3$) controlam pelos níveis de base de cada dimensão.\n\n-   As interações duplas ($\\beta_4, \\beta_5, \\beta_6$) controlam pelos efeitos DiD em subgrupos (o DiD entre período e estado, o DiD entre estado e grupo, e o DiD entre período e grupo).\n\n-   O coeficiente da interação tripla, $\\beta_7$, é o **estimador DDD**. Ele captura a mudança diferencial na tendência temporal do grupo de tratamento que está acima e além de todas as outras tendências de nível inferior.\n\nAo estimar este modelo com os dados do exemplo, o coeficiente $\\beta_7$ seria aproximadamente **3.22**, confirmando nossa intuição e cálculo manual.\n\n### Interpretação dos Resultados\n\nO estimador DDD de aproximadamente **3.22** nos diz que, após controlar pelas tendências divergentes entre os estados Tratado e Controle (capturadas pelo grupo de Comparação), o efeito causal da desoneração sobre o emprego no grupo Alvo é de cerca de 3.22 unidades.\n\nEste resultado é **menor** do que o DiD simples de 3.86 que obtivemos para o grupo Alvo. A diferença de 0.64 representa o **viés** que estava inflando nossa estimativa inicial, causado pela violação da hipótese de tendências paralelas.\n\n## Quando Usar o DDD?\n\nO método de Triplas Diferenças é particularmente útil nas seguintes situações:\n\n1.  **Suspeita de Violação de Tendências Paralelas**: Quando há razões teóricas ou empíricas para acreditar que o grupo de controle tem uma trajetória diferente do grupo de tratamento, mesmo na ausência da política.\n\n2.  **Disponibilidade de um Grupo de Comparação Adequado**: É necessário identificar um grupo que seja afetado pelos mesmos choques que o grupo de controle, mas que não seja afetado pela política de interesse.\n\n3.  **Alguns exemplos específicos**\n\n-   **Políticas Implementadas em Diferentes Regiões**: Quando uma política é implementada em alguns estados ou municípios, mas não em outros, e há preocupações sobre diferenças regionais em tendências econômicas.\n\n-   **Setores com Dinâmicas Distintas**: Quando diferentes setores econômicos têm trajetórias de crescimento naturalmente diferentes, e a política afeta apenas alguns deles.\n\n## Hipóteses do DDD\n\nPara que o estimador DDD identifique o efeito causal, as seguintes hipóteses devem ser satisfeitas:\n\n1.  **Tendências Paralelas Condicionais**: Na ausência do tratamento, a diferença nas tendências entre o grupo Alvo e o grupo de Comparação seria a mesma no Estado Tratado e no Estado de Controle. Formalmente:\n\n2.  **Ausência de Efeitos de Transbordamento (Spillovers)**: O tratamento no grupo Alvo do Estado Tratado não afeta os resultados dos outros grupos.\n\n3.  **Composição Estável**: A composição dos grupos não muda de forma endógena em resposta à política.\n\n4.  **Grupo de Comparação Válido**: O grupo de Comparação deve ser afetado pelos mesmos choques confundidores que o grupo Alvo, mas não pela política de interesse.\n\n## Limitações e Cuidados\n\nApesar de sua robustez, o DDD tem limitações importantes:\n\n1.  **Requisitos de Dados Mais Exigentes**: O DDD requer dados para quatro grupos (duas dimensões de tratamento), o que pode não estar disponível em todos os contextos.\n\n2.  **Interpretação Mais Complexa**: A lógica do DDD é menos intuitiva do que o DiD simples, o que pode dificultar a comunicação dos resultados.\n\n3.  **Hipóteses Mais Fortes**: Embora o DDD relaxe a hipótese de tendências paralelas do DiD, ele impõe sua própria hipótese de tendências paralelas condicionais, que também pode ser violada.\n\n4.  **Escolha do Grupo de Comparação**: A validade do DDD depende criticamente da escolha adequada do grupo de Comparação. Se este grupo não for afetado pelos mesmos choques que o grupo de controle, o estimador DDD será enviesado.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}