<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Caio Lopes">
<meta name="dcterms.date" content="2025-04-19">

<title>APP - RDD</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">APP</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">About</a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"><i class="bi bi-github" role="img">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"><i class="bi bi-twitter" role="img">
</i> 
 </a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">RDD</h1>
                                <div class="quarto-categories">
                <div class="quarto-category">Ensino</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">Author</div>
      <div class="quarto-title-meta-contents">
               <p>Caio Lopes </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">Published</div>
      <div class="quarto-title-meta-contents">
        <p class="date">April 19, 2025</p>
      </div>
    </div>
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">




<section id="introdução" class="level1">
<h1>Introdução</h1>
<p>O <em>Regression Discontinuity Design</em> (RDD), ou Regressão com Descontinuidade, é mais um método para estimação do efeito causais (treatment effect).</p>
<p>Sua a fundamentação teórica, encontra-se no trabalho seminal de <strong>Hahn, Todd e Van der Klaauw (2001)</strong> [1], que formalizou as condições sob as quais o RDD identifica um efeito de tratamento causal. Em seguida, faremos um paralelo entre duas aplicações empíricas clássicas:</p>
<ol type="1">
<li><p><strong>Lee (2008)</strong> [2]: O estudo sobre a vantagem eleitoral de incumbentes nos EUA, um exemplo de como uma regra (vencer por uma margem mínima) cria um quase-experimento.</p></li>
<li><p><strong>Carpenter &amp; Dobkin (2009)</strong> [3]: A análise do efeito da idade mínima para consumo de álcool sobre a mortalidade, um caso onde a variável de tratamento é perfeitamente determinada por uma lei.</p></li>
</ol>
</section>
<section id="a-fundação-teórica" class="level1">
<h1>A Fundação Teórica</h1>
<p>O artigo de Hahn, Todd e Van der Klaauw (HTV) foi crucial para estabelecer a credibilidade do RDD como um método quase-experimental. Eles mostraram que, sob hipoteses relativamente fracas, o RDD pode identificar um efeito de tratamento local com a mesma validade de um experimento aleatório.</p>
<section id="o-setup-básico-do-rdd" class="level2">
<h2 class="anchored" data-anchor-id="o-setup-básico-do-rdd">O Setup Básico do RDD</h2>
<p>Imagine uma situação onde uma intervenção (tratamento) é atribuída com base em uma <strong>variável de continuidade</strong> (<em>running variable</em>), que chamaremos de <code>Z</code>. Existe um <strong>ponto de corte</strong> (<em>cutoff</em>), <code>c</code>, que determina quem recebe o tratamento. Por exemplo, <code>Z</code> pode ser a nota de um aluno em um exame, e todos com nota <code>Z &gt;= c</code> recebem uma bolsa de estudos.</p>
<p>O RDD explora a ideia de que indivíduos com valores de <code>Z</code> muito próximos ao cutoff <code>c</code>, mas de lados opostos, são, em média, muito semelhantes em todas as outras características (observáveis e não observáveis). A única diferença sistemática entre eles é o recebimento do tratamento. Portanto, qualquer “salto” ou <strong>descontinuidade</strong> na variável de resultado nesse ponto pode ser atribuído ao efeito causal do tratamento.</p>
</section>
<section id="sharp-vs.-fuzzy-rdd" class="level2">
<h2 class="anchored" data-anchor-id="sharp-vs.-fuzzy-rdd">Sharp vs.&nbsp;Fuzzy RDD</h2>
<p>HTV formalizam a distinção entre dois tipos de RDD:</p>
<ol type="1">
<li><p><strong>Sharp RDD (RDD Nítido)</strong>: O tratamento é uma função determinística do cutoff. Todos os indivíduos com <code>Z &gt;= c</code> recebem o tratamento, e ninguém com <code>Z &lt; c</code> o recebe. A probabilidade de tratamento salta de 0 para 1 exatamente no cutoff.</p></li>
<li><p><strong>Fuzzy RDD (RDD Difuso)</strong>: O cutoff influencia a <em>probabilidade</em> de receber o tratamento, mas não a determina perfeitamente. Por exemplo, uma bolsa de estudos pode ser <em>oferecida</em> a todos com <code>Z &gt;= c</code>, mas nem todos a aceitam. Nesse caso, a probabilidade de tratamento salta de um valor <code>p_abaixo</code> para um valor <code>p_acima</code> no cutoff, mas não necessariamente de 0 para 1.</p></li>
</ol>
</section>
<section id="a-condição-de-identificação-fundamental" class="level2">
<h2 class="anchored" data-anchor-id="a-condição-de-identificação-fundamental">A Condição de Identificação Fundamental</h2>
<p>A grande contribuição de HTV foi esclarecer o pressuposto central que permite a identificação do efeito causal. Este pressuposto é a <strong>continuidade das funções de regressão dos resultados potenciais no cutoff</strong>.</p>
<p>Vamos definir os resultados potenciais:</p>
<ul>
<li><code>Y(1)</code>: O resultado que um indivíduo teria se recebesse o tratamento.</li>
<li><code>Y(0)</code>: O resultado que o mesmo indivíduo teria se não recebesse o tratamento.</li>
</ul>
<p>O pressuposto fundamental do RDD é que as médias condicionais de <code>Y(1)</code> e <code>Y(0)</code> são contínuas em relação à variável de continuidade <code>Z</code> no ponto <code>c</code>.</p>
<blockquote class="blockquote">
<p><strong>Pressuposto de Continuidade (HTV, 2001):</strong> As funções <code>E[Y(1) | Z=z]</code> e <code>E[Y(0) | Z=z]</code> são contínuas em <code>z=c</code>.</p>
</blockquote>
<p>Em palavras simples, isso significa que, na ausência do tratamento, a relação entre a variável de continuidade e o resultado seria suave e não teria um salto no cutoff. Se essa condição for válida, qualquer salto observado no resultado real no cutoff deve ser atribuído ao tratamento.</p>
</section>
<section id="o-que-o-rdd-estima-o-late" class="level2">
<h2 class="anchored" data-anchor-id="o-que-o-rdd-estima-o-late">O que o RDD Estima: O LATE</h2>
<p>Sob este pressuposto, HTV mostram que o RDD identifica o <strong>Efeito Médio do Tratamento Local</strong> (<em>Local Average Treatment Effect</em> - LATE) no cutoff. O estimador é a razão entre o salto no resultado e o salto na probabilidade de tratamento:</p>
<p><span class="math display">\[ \text{LATE} = \frac{\lim_{z \to c^+} E[Y|Z=z] - \lim_{z \to c^-} E[Y|Z=z]}{\lim_{z \to c^+} E[D|Z=z] - \lim_{z \to c^-} E[D|Z=z]} \]</span></p>
<p>Onde: - <code>Y</code> é o resultado observado. - <code>D</code> é o indicador de tratamento (0 ou 1). - O numerador é o “salto” no resultado no cutoff. - O denominador é o “salto” na probabilidade de tratamento no cutoff.</p>
<p>No caso de um <strong>Sharp RDD</strong>, o denominador é 1 (o salto na probabilidade é de 0 para 1), então o LATE é simplesmente o tamanho do salto no resultado.</p>
</section>
</section>
<section id="parte-2-o-paralelo-teórico-nas-aplicações" class="level1">
<h1>Parte 2: O Paralelo Teórico nas Aplicações</h1>
<p>Os estudos de Lee (2008) e Carpenter &amp; Dobkin (2009) são exemplos perfeitos que ilustram a teoria de HTV em contextos muito diferentes. Ambos são <strong>Sharp RDDs</strong> e sua credibilidade reside na impossibilidade (ou grande dificuldade) de manipular a variável de continuidade.</p>
<p>Vamos comparar os dois estudos lado a lado:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th>Característica</th>
<th>Lee (2008): Vantagem de Incumbência</th>
<th>Carpenter &amp; Dobkin (2009): Álcool e Mortalidade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Questão Causal</strong></td>
<td>Qual o efeito causal de vencer uma eleição sobre os votos na próxima?</td>
<td>Qual o efeito causal do acesso legal ao álcool sobre a mortalidade?</td>
</tr>
<tr class="even">
<td><strong>Variável de Continuidade (Z)</strong></td>
<td>Margem de vitória do partido Democrata na eleição <em>t-1</em>.</td>
<td>Idade do indivíduo.</td>
</tr>
<tr class="odd">
<td><strong>Cutoff (c)</strong></td>
<td>0 (zero).</td>
<td>21 anos.</td>
</tr>
<tr class="even">
<td><strong>Tratamento (D)</strong></td>
<td>Vencer a eleição em <em>t-1</em> (ser o incumbente).</td>
<td>Ter permissão legal para comprar e consumir álcool.</td>
</tr>
<tr class="odd">
<td><strong>Resultado (Y)</strong></td>
<td>Porcentagem de votos do partido Democrata na eleição <em>t</em>.</td>
<td>Taxa de mortalidade (por todas as causas, acidentes, suicídio, etc.).</td>
</tr>
<tr class="even">
<td><strong>Tipo de RDD</strong></td>
<td><strong>Sharp RDD</strong>. A vitória é uma função determinística da margem &gt; 0.</td>
<td><strong>Sharp RDD</strong>. A permissão legal é uma função determinística da idade.</td>
</tr>
</tbody>
</table>
<section id="a-lógica-da-identificação-em-cada-contexto" class="level2">
<h2 class="anchored" data-anchor-id="a-lógica-da-identificação-em-cada-contexto">A Lógica da Identificação em Cada Contexto</h2>
<section id="lee-2008-eleições-como-experimentos-aleatórios" class="level3">
<h3 class="anchored" data-anchor-id="lee-2008-eleições-como-experimentos-aleatórios">Lee (2008): Eleições como Experimentos Aleatórios</h3>
<p>A genialidade do estudo de Lee é argumentar que, em eleições muito disputadas (com margem de vitória próxima de zero), o vencedor é <strong>tão bom quanto aleatório</strong>. Um candidato que vence por 0.1% dos votos é, em média, extremamente semelhante a um que perde por 0.1%. Eles têm financiamento, qualidade e apelo eleitoral virtualmente idênticos.</p>
<ul>
<li><strong>Validade do Pressuposto de Continuidade</strong>: É plausível que a porcentagem de votos na próxima eleição (<code>Y</code>) variaria suavemente com a margem de vitória anterior (<code>Z</code>) se não houvesse o “prêmio” da incumbência. Não há razão para acreditar que um candidato que vence por 0.1% teria uma trajetória de votos futura drasticamente diferente de um que perde por 0.1%, a não ser pelo fato de ter vencido.</li>
<li><strong>Impossibilidade de Manipulação</strong>: É extremamente difícil para um candidato controlar o resultado de uma eleição com precisão suficiente para garantir uma vitória por uma margem mínima.</li>
</ul>
<p>O estudo encontra um salto de cerca de <strong>7-8 pontos percentuais</strong> na porcentagem de votos na eleição seguinte, que é o LATE da incumbência.</p>
</section>
<section id="carpenter-dobkin-2009-leis-como-descontinuidades-perfeitas" class="level3">
<h3 class="anchored" data-anchor-id="carpenter-dobkin-2009-leis-como-descontinuidades-perfeitas">Carpenter &amp; Dobkin (2009): Leis como Descontinuidades Perfeitas</h3>
<p>Este estudo explora uma regra institucional ainda mais rígida: a idade mínima para o consumo de álcool (MLDA - <em>Minimum Legal Drinking Age</em>).</p>
<ul>
<li><strong>Validade do Pressuposto de Continuidade</strong>: A variável de continuidade é a idade. É altamente plausível que a taxa de mortalidade (<code>Y</code>) mude suavemente com a idade (<code>Z</code>). Não há razão biológica ou social para que a mortalidade de uma pessoa salte abruptamente no dia do seu 21º aniversário, a não ser por uma mudança de comportamento induzida por uma nova permissão legal.</li>
<li><strong>Impossibilidade de Manipulação</strong>: A idade de uma pessoa é uma variável que não pode ser manipulada. Ninguém pode escolher fazer 21 anos mais cedo para beber legalmente. Isso torna o design RDD extremamente crível neste contexto.</li>
</ul>
<p>O estudo encontra um salto discreto de cerca de <strong>9% na taxa de mortalidade</strong> geral logo após os 21 anos, atribuído ao aumento do consumo de álcool e comportamentos de risco associados.</p>
</section>
</section>
</section>
<section id="conclusão-a-unidade-na-diversidade-do-rdd" class="level1">
<h1>Conclusão: A Unidade na Diversidade do RDD</h1>
<p>Ao comparar os estudos de Lee (2008) e Carpenter &amp; Dobkin (2009) através das lentes teóricas de Hahn, Todd e Van der Klaauw (2001), vemos um padrão unificador. Ambos os estudos, embora aplicados a domínios completamente diferentes (ciência política e saúde pública), compartilham a mesma lógica fundamental:</p>
<ol type="1">
<li><strong>Identificam uma regra arbitrária</strong> (vencer uma eleição, atingir 21 anos) que gera uma descontinuidade no tratamento.</li>
<li><strong>Argumentam que a variável de continuidade não é manipulável</strong> em torno do cutoff, garantindo que a comparação local seja válida.</li>
<li><strong>Demonstram visualmente e estimam quantitativamente um “salto”</strong> na variável de resultado, que, sob o pressuposto de continuidade, pode ser interpretado como um efeito causal local.</li>
</ol>
<p>O RDD, portanto, nos permite transformar dados observacionais em evidências quase-experimentais, fornecendo respostas críveis para algumas das questões mais importantes das ciências sociais aplicadas.</p>
</section>
<section id="replicação-de-carpenter-dobkin-2009" class="level1">
<h1>Replicação de Carpenter &amp; Dobkin (2009)</h1>
<p>O Blog de Leppert (2020) [4] traz um tutorial de como aplicar o RDD por da replicação de Carpenter &amp; Dobkin (2009) usando o pacote <code>rddtools</code>.</p>
<p>Primeiro, vamos carregar todos os pacotes necessários para a análise.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Instalar pacotes se necessário</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"dplyr"</span>)) <span class="fu">install.packages</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"ggplot2"</span>)) <span class="fu">install.packages</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"rddtools"</span>)) <span class="fu">install.packages</span>(<span class="st">"rddtools"</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">require</span>(<span class="st">"magrittr"</span>)) <span class="fu">install.packages</span>(<span class="st">"magrittr"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Carregar pacotes</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rddtools)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Agora, vamos carregar os dados reais do estudo (estão disponíveis no github de Leppert</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>carpenter_dobkin_2009 <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"carpenter_dobkin_2009.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Vamos visualizar os dados. Há um salto notável na taxa de mortalidade aos 21 anos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>carpenter_dobkin_2009 <span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> agecell, <span class="at">y =</span> all)) <span class="sc">+</span> </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">21</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span> </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">20.4</span>, <span class="at">y =</span> <span class="dv">105</span>, <span class="at">label =</span> <span class="st">"Minimum Drinking Age"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">size=</span><span class="dv">4</span>) <span class="sc">+</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Mortality rate (per 100.000)"</span>,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age (binned)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` instead.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot_scatter_tutorial-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>O RDD pode ser estimado por OLS. A primeira regressão aplica a mesma inclinação em ambos os lados do cutoff.</p>
<p>Primeiro, criamos uma variável dummy (<code>threshold</code>). Em seguida, especificamos um modelo linear para regredir a mortalidade (<code>all</code>) na dummy <code>threshold</code> e na idade (<code>agecell</code>) centrada em 21.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>lm_same_slope <span class="ot">&lt;-</span> carpenter_dobkin_2009 <span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">threshold =</span> <span class="fu">ifelse</span>(agecell <span class="sc">&gt;=</span> <span class="dv">21</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%$%</span> </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(all <span class="sc">~</span> threshold <span class="sc">+</span> <span class="fu">I</span>(agecell <span class="sc">-</span> <span class="dv">21</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_same_slope)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = all ~ threshold + I(agecell - 21))

Residuals:
    Min      1Q  Median      3Q     Max 
-5.0559 -1.8483  0.1149  1.4909  5.8043 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      91.8414     0.8050 114.083  &lt; 2e-16 ***
threshold         7.6627     1.4403   5.320 3.15e-06 ***
I(agecell - 21)  -0.9747     0.6325  -1.541     0.13    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.493 on 45 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.5946,    Adjusted R-squared:  0.5765 
F-statistic: 32.99 on 2 and 45 DF,  p-value: 1.508e-09</code></pre>
</div>
</div>
<p>O pacote <code>rddtools</code> simplifica este processo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rdd_data</span>(<span class="at">y =</span> carpenter_dobkin_2009<span class="sc">$</span>all, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> carpenter_dobkin_2009<span class="sc">$</span>agecell, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">cutpoint =</span> <span class="dv">21</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rdd_reg_lm</span>(<span class="at">slope =</span> <span class="st">"same"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ ., data = dat_step1, weights = weights)

Residuals:
    Min      1Q  Median      3Q     Max 
-5.0559 -1.8483  0.1149  1.4909  5.8043 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  91.8414     0.8050 114.083  &lt; 2e-16 ***
D             7.6627     1.4403   5.320 3.15e-06 ***
x            -0.9747     0.6325  -1.541     0.13    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.493 on 45 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.5946,    Adjusted R-squared:  0.5765 
F-statistic: 32.99 on 2 and 45 DF,  p-value: 1.508e-09</code></pre>
</div>
</div>
<p>O gráfico mostra a linha de regressão ajustada, que tem a mesma inclinação em ambos os lados do cutoff.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>carpenter_dobkin_2009 <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(agecell, all) <span class="sc">%&gt;%</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">threshold =</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>(agecell <span class="sc">&gt;=</span> <span class="dv">21</span>, <span class="dv">1</span>, <span class="dv">0</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> agecell, <span class="at">y =</span> all)) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> threshold)) <span class="sc">+</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>) <span class="sc">+</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">21</span>, <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Mortality rate (per 100.000)"</span>,</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age (binned)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: The `&lt;scale&gt;` argument of `guides()` cannot be `FALSE`. Use "none" instead as
of ggplot2 3.3.4.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot_same_slope_tutorial-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>O coeficiente da variável dummy <code>threshold</code> é o efeito médio do tratamento. Em média, a taxa de mortalidade por 100.000 para indivíduos que atingem a idade mínima para beber é <strong>7.66</strong> pontos mais alta.</p>
<p>A segunda regressão aplica inclinações diferentes em ambos os lados do cutoff. Isso é alcançado especificando uma interação entre a dummy <code>threshold</code> e a idade centrada.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>lm_different_slope <span class="ot">&lt;-</span> carpenter_dobkin_2009 <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">threshold =</span> <span class="fu">ifelse</span>(agecell <span class="sc">&gt;=</span> <span class="dv">21</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%$%</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(all <span class="sc">~</span> threshold <span class="sc">+</span> <span class="fu">I</span>(agecell <span class="sc">-</span> <span class="dv">21</span>) <span class="sc">+</span> threshold<span class="sc">:</span><span class="fu">I</span>(agecell <span class="sc">-</span> <span class="dv">21</span>))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_different_slope)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = all ~ threshold + I(agecell - 21) + threshold:I(agecell - 
    21))

Residuals:
   Min     1Q Median     3Q    Max 
-4.368 -1.787  0.117  1.108  5.341 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                93.6184     0.9325 100.399  &lt; 2e-16 ***
threshold                   7.6627     1.3187   5.811  6.4e-07 ***
I(agecell - 21)             0.8270     0.8189   1.010  0.31809    
threshold:I(agecell - 21)  -3.6034     1.1581  -3.111  0.00327 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.283 on 44 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.6677,    Adjusted R-squared:  0.645 
F-statistic: 29.47 on 3 and 44 DF,  p-value: 1.325e-10</code></pre>
</div>
</div>
<p>No <code>rddtools</code>, usamos o argumento <code>slope = "separate"</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rdd_data</span>(<span class="at">y =</span> carpenter_dobkin_2009<span class="sc">$</span>all, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> carpenter_dobkin_2009<span class="sc">$</span>agecell, </span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">cutpoint =</span> <span class="dv">21</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rdd_reg_lm</span>(<span class="at">slope =</span> <span class="st">"separate"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ ., data = dat_step1, weights = weights)

Residuals:
   Min     1Q Median     3Q    Max 
-4.368 -1.787  0.117  1.108  5.341 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  93.6184     0.9325 100.399  &lt; 2e-16 ***
D             7.6627     1.3187   5.811  6.4e-07 ***
x             0.8270     0.8189   1.010  0.31809    
x_right      -3.6034     1.1581  -3.111  0.00327 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.283 on 44 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.6677,    Adjusted R-squared:  0.645 
F-statistic: 29.47 on 3 and 44 DF,  p-value: 1.325e-10</code></pre>
</div>
</div>
<p>O gráfico mostra as diferentes inclinações.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>carpenter_dobkin_2009 <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(agecell, all) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">threshold =</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>(agecell <span class="sc">&gt;=</span> <span class="dv">21</span>, <span class="dv">1</span>, <span class="dv">0</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> agecell, <span class="at">y =</span> all, <span class="at">color =</span> threshold)) <span class="sc">+</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">21</span>, <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Mortality rate (per 100.000)"</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age (binned)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot_different_slope_tutorial-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Esta abordagem não altera a interpretação do efeito do tratamento! Em média, a taxa de mortalidade por 100.000 para indivíduos que atingem a idade mínima para beber é <strong>7.66</strong> pontos mais alta.</p>
<section id="análise-de-sensibilidade-modificando-a-forma-funcional" class="level3">
<h3 class="anchored" data-anchor-id="análise-de-sensibilidade-modificando-a-forma-funcional">Análise de Sensibilidade: Modificando a Forma Funcional</h3>
<p>Deve-se prestar atenção especial à especificação da forma funcional.</p>
<p>Abaixo, modelamos uma relação quadrática entre idade e mortalidade.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>lm_quadratic <span class="ot">&lt;-</span> carpenter_dobkin_2009 <span class="sc">%&gt;%</span> </span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">threshold =</span> <span class="fu">ifelse</span>(agecell <span class="sc">&gt;=</span> <span class="dv">21</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%$%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(all <span class="sc">~</span> threshold <span class="sc">+</span> <span class="fu">I</span>(agecell <span class="sc">-</span> <span class="dv">21</span>) <span class="sc">+</span> <span class="fu">I</span>((agecell <span class="sc">-</span><span class="dv">21</span>)<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> threshold<span class="sc">:</span><span class="fu">I</span>(agecell <span class="sc">-</span> <span class="dv">21</span>) <span class="sc">+</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>       threshold<span class="sc">:</span><span class="fu">I</span>((agecell <span class="sc">-</span> <span class="dv">21</span>)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_quadratic)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = all ~ threshold + I(agecell - 21) + I((agecell - 
    21)^2) + threshold:I(agecell - 21) + threshold:I((agecell - 
    21)^2))

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3343 -1.3946  0.1849  1.2848  5.0817 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    93.0729     1.4038  66.301  &lt; 2e-16 ***
threshold                       9.5478     1.9853   4.809 1.97e-05 ***
I(agecell - 21)                -0.8306     3.2901  -0.252    0.802    
I((agecell - 21)^2)            -0.8403     1.6153  -0.520    0.606    
threshold:I(agecell - 21)      -6.0170     4.6529  -1.293    0.203    
threshold:I((agecell - 21)^2)   2.9042     2.2843   1.271    0.211    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.285 on 42 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.6821,    Adjusted R-squared:  0.6442 
F-statistic: 18.02 on 5 and 42 DF,  p-value: 1.624e-09</code></pre>
</div>
</div>
<p>Em <code>rdd_reg_lm()</code>, modificamos o argumento <code>order = 2</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rdd_data</span>(<span class="at">y =</span> carpenter_dobkin_2009<span class="sc">$</span>all, </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> carpenter_dobkin_2009<span class="sc">$</span>agecell, </span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">cutpoint =</span> <span class="dv">21</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rdd_reg_lm</span>(<span class="at">slope =</span> <span class="st">"separate"</span>, <span class="at">order =</span> <span class="dv">2</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summary</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ ., data = dat_step1, weights = weights)

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3343 -1.3946  0.1849  1.2848  5.0817 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  93.0729     1.4038  66.301  &lt; 2e-16 ***
D             9.5478     1.9853   4.809 1.97e-05 ***
x            -0.8306     3.2901  -0.252    0.802    
`x^2`        -0.8403     1.6153  -0.520    0.606    
x_right      -6.0170     4.6529  -1.293    0.203    
`x^2_right`   2.9042     2.2843   1.271    0.211    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.285 on 42 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.6821,    Adjusted R-squared:  0.6442 
F-statistic: 18.02 on 5 and 42 DF,  p-value: 1.624e-09</code></pre>
</div>
</div>
<p>À direita do cutoff, este modelo parece se ajustar melhor aos dados!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>carpenter_dobkin_2009 <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(agecell, all) <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">threshold =</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>(agecell <span class="sc">&gt;=</span> <span class="dv">21</span>, <span class="dv">1</span>, <span class="dv">0</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> agecell, <span class="at">y =</span> all, <span class="at">color =</span> threshold)) <span class="sc">+</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>,</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x <span class="sc">^</span> <span class="dv">2</span>),</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>              <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>) <span class="sc">+</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">21</span>, <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Mortality rate (per 100.000)"</span>,</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age (binned)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot_quadratic_tutorial-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Em média, a taxa de mortalidade por 100.000 para indivíduos que atingem a idade mínima para beber é agora <strong>9.55</strong> pontos mais alta.</p>
</section>
<section id="análise-de-sensibilidade-tamanho-do-amostra-sensibilidade-ao-bandwidth" class="level3">
<h3 class="anchored" data-anchor-id="análise-de-sensibilidade-tamanho-do-amostra-sensibilidade-ao-bandwidth">Análise de Sensibilidade: Tamanho do amostra (Sensibilidade ao Bandwidth)</h3>
<p>É aconselhável verificar a sensibilidade dos resultados em relação à limitação do tamanho da amostra.</p>
<p>Em vez de usar toda a faixa de idade, usamos apenas indivíduos com idade entre 20 e 22 anos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>lm_sensitivity <span class="ot">&lt;-</span> carpenter_dobkin_2009 <span class="sc">%&gt;%</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(agecell <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">&amp;</span> agecell <span class="sc">&lt;=</span> <span class="dv">22</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">threshold =</span> <span class="fu">ifelse</span>(agecell <span class="sc">&gt;=</span> <span class="dv">21</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">%$%</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">lm</span>(all <span class="sc">~</span> threshold <span class="sc">+</span> <span class="fu">I</span>(agecell <span class="sc">-</span> <span class="dv">21</span>) <span class="sc">+</span> threshold<span class="sc">:</span><span class="fu">I</span>(agecell <span class="sc">-</span> <span class="dv">21</span>))</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(lm_sensitivity)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = all ~ threshold + I(agecell - 21) + threshold:I(agecell - 
    21))

Residuals:
    Min      1Q  Median      3Q     Max 
-4.3038 -0.9132 -0.1746  1.1758  4.3307 

Coefficients:
                          Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                 92.524      1.370  67.550  &lt; 2e-16 ***
threshold                    9.753      1.937   5.035 6.34e-05 ***
I(agecell - 21)             -1.612      2.407  -0.669    0.511    
threshold:I(agecell - 21)   -3.289      3.405  -0.966    0.346    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.366 on 20 degrees of freedom
  (2 observations deleted due to missingness)
Multiple R-squared:  0.7161,    Adjusted R-squared:  0.6735 
F-statistic: 16.82 on 3 and 20 DF,  p-value: 1.083e-05</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>carpenter_dobkin_2009 <span class="sc">%&gt;%</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(agecell <span class="sc">&gt;=</span> <span class="dv">20</span> <span class="sc">&amp;</span> agecell <span class="sc">&lt;=</span> <span class="dv">22</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(agecell, all) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">threshold =</span> <span class="fu">as.factor</span>(<span class="fu">ifelse</span>(agecell <span class="sc">&gt;=</span> <span class="dv">21</span>, <span class="dv">1</span>, <span class="dv">0</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> agecell, <span class="at">y =</span> all, <span class="at">color =</span> threshold)) <span class="sc">+</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Accent"</span>) <span class="sc">+</span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">guides</span>(<span class="at">color =</span> <span class="cn">FALSE</span>) <span class="sc">+</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">21</span>, <span class="at">color =</span> <span class="st">"red"</span>,</span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">size =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"Mortality rate (per 100.000)"</span>,</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Age (binned)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/plot_sensitivity_tutorial-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Este resultado é bastante semelhante à abordagem anterior com o modelo quadrático. Em média, a taxa de mortalidade por 100.000 para indivíduos que atingem a idade mínima para beber é <strong>9.75</strong> pontos mais alta.</p>
<p>Usando o <code>rddtools</code> podemos fazer a análise por ordem do polinômio</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>rdd_sens <span class="ot">&lt;-</span><span class="fu">rdd_data</span>(<span class="at">y =</span> carpenter_dobkin_2009<span class="sc">$</span>all, </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> carpenter_dobkin_2009<span class="sc">$</span>agecell, </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">cutpoint =</span> <span class="dv">21</span>) </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>rdd_sens_ik <span class="ot">&lt;-</span> <span class="fu">rdd_bw_ik</span>(rdd_sens)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>rdd_sens2 <span class="ot">&lt;-</span> <span class="fu">rdd_reg_lm</span>(<span class="at">rdd_object=</span>rdd_sens, <span class="at">order=</span><span class="dv">2</span>, <span class="at">bw=</span>rdd_sens_ik) </span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plotSensi</span>(rdd_sens2, <span class="at">from=</span><span class="dv">1</span>, <span class="at">to=</span><span class="dv">5</span>, <span class="at">by=</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/rddtools_Bandwidth-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="análise-de-sensibilidade-placebo-do-cutoff" class="level3">
<h3 class="anchored" data-anchor-id="análise-de-sensibilidade-placebo-do-cutoff">Análise de Sensibilidade: placebo do cutoff</h3>
<p>Podemos repetir a análise para placebos falsos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotPlacebo</span>(rdd_sens2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/rddtools_placebo-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="referências" class="level1">
<h1>Referências</h1>
<p>[1] Hahn, J., Todd, P., &amp; Van der Klaauw, W. (2001). Identification and Estimation of Treatment Effects with a Regression-Discontinuity Design. <em>Econometrica, 69</em>(1), 201-209.</p>
<p>[2] Lee, D. S. (2008). Randomized experiments from non-random selection in U.S. House elections. <em>Journal of Econometrics</em>, 142(2), 675-697.</p>
<p>[3] Carpenter, C., &amp; Dobkin, C. (2009). The Effect of Alcohol Consumption on Mortality: Regression Discontinuity Evidence from the Minimum Drinking Age. <em>American Economic Journal: Applied Economics, 1</em>(1), 164–182.</p>
<p>[4] Leppert, P. R Tutorial: Regression Discontinuity Design. Disponível em: https://rpubs.com/phle/r_tutorial_regression_discontinuity_design. Acesso em: 01/12/2025.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>